### PR TITLE
Tag with _syslogpriparsefailure the events that refer to facility events not present in the dictionary

### LINKED ISSUE #12: Too big long value for priority crashes the pipeline with RangeError
**Logstash information**:

Please include the following information:

1. Logstash version (e.g. `bin/logstash --version`) any 
2. Logstash installation source (e.g. built from source, with a package manager: DEB/RPM, expanded from tar or zip archive, docker)
3. How is Logstash being run (e.g. as a service/service manager: systemd, upstart, etc. Via command line, docker/kubernetes) indifferent
4. How was the Logstash Plugin installed already packaged with Logstash

**JVM** (e.g. `java -version`):

If the affected version of Logstash is 7.9 (or earlier), or if it is NOT using the bundled JDK or using the 'no-jdk' version in 7.10 (or higher), please provide the following information:

1. JVM version (`java -version`)
2. JVM installation source (e.g. from the Operating System's package manager, from source, etc).
3. Value of the `JAVA_HOME` environment variable if set.

**OS version** (`uname -a` if on a Unix-like system): any

**Description of the problem including expected versus actual behavior**:
Given a value too big for the priority field crashes the pipeline.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) pipeline definition(s), settings, locale, etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. Run the pipeline:
 ```
 input {
  generator {
    message => '{"syslog_test_pri": 29999999999999999999999, "raw_data": "<240>Dec 12 11:22:33 mymachine failed for myuser on /dev/pts/0"}'
    codec => json
    count => 1
  }
}

filter {
  syslog_pri {
    ecs_compatibility => "v1"
    syslog_pri_field_name => "syslog_test_pri"
  }
}

output {
  stdout {
    codec => rubydebug
  }
}
```
It fails with 
```
(RangeError) bignum too big to convert into `long'
```

**Provide logs (if relevant)**:
```
[2022-12-12T15:45:14,310][INFO ][logstash.javapipeline    ][main] Pipeline started {"pipeline.id"=>"main"}
[2022-12-12T15:45:14,331][INFO ][logstash.agent           ] Pipelines running {:count=>1, :running_pipelines=>[:main], :non_running_pipelines=>[]}
[2022-12-12T15:45:14,449][ERROR][logstash.javapipeline    ][main] Pipeline worker error, the pipeline will be stopped {:pipeline_id=>"main", :error=>"(RangeError) bignum too big to convert into `long'", :exception=>Java::OrgJrubyExceptions::RangeError, :backtrace=>["org.jruby.RubyArray.[](org/jruby/RubyArray.java:1545)", "RUBY.parse_pri(/home/andrea/workspace/logstash_andsel/vendor/bundle/jruby/2.6.0/gems/logstash-filter-syslog_pri-3.1.1/lib/logstash/filters/syslog_pri.rb:108)", "RUBY.filter(/home/andrea/workspace/logstash_andsel/vendor/bundle/jruby/2.6.0/gems/logstash-filter-syslog_pri-3.1.1/lib/logstash/filters/syslog_pri.rb:81)", "RUBY.do_filter(/home/andrea/workspace/logstash_andsel/logstash-core/lib/logstash/filters/base.rb:159)", "RUBY.multi_filter(/home/andrea/workspace/logstash_andsel/logstash-core/lib/logstash/filters/base.rb:178)", "org.jruby.RubyArray.each(org/jruby/RubyArray.java:1865)", "RUBY.multi_filter(/home/andrea/workspace/logstash_andsel/logstash-core/lib/logstash/filters/base.rb:175)", "org.logstash.config.ir.compiler.AbstractFilterDelegatorExt.multi_filter(org/logstash/config/ir/compiler/AbstractFilterDelegatorExt.java:134)", "RUBY.start_workers(/home/andrea/workspace/logstash_andsel/logstash-core/lib/logstash/java_pipeline.rb:301)"], :thread=>"#<Thread:0x39f36dc9@/home/andrea/workspace/logstash_andsel/logstash-core/lib/logstash/java_pipeline.rb:131 sleep>"}
[2022-12-12T15:45:14,451][INFO ][logstash.javapipeline    ][main] Pipeline terminated {"pipeline.id"=>"main"}
[2022-12-12T15:45:14,836][INFO ][logstash.pipelinesregistry] Removed pipeline from registry successfully {:pipeline_id=>:main}
```

Tracelog:
```
org.jruby.RubyArray.[](org/jruby/RubyArray.java:1545)
RUBY.parse_pri(/home/andrea/workspace/logstash_andsel/vendor/bundle/jruby/2.6.0/gems/logstash-filter-syslog_pri-3.1.1/lib/logstash/filters/syslog_pri.rb:108)
RUBY.filter(/home/andrea/workspace/logstash_andsel/vendor/bundle/jruby/2.6.0/gems/logstash-filter-syslog_pri-3.1.1/lib/logstash/filters/syslog_pri.rb:81)
RUBY.do_filter(/home/andrea/workspace/logstash_andsel/logstash-core/lib/logstash/filters/base.rb:159)
RUBY.multi_filter(/home/andrea/workspace/logstash_andsel/logstash-core/lib/logstash/filters/base.rb:178)
org.jruby.RubyArray.each(org/jruby/RubyArray.java:1865)
RUBY.multi_filter(/home/andrea/workspace/logstash_andsel/logstash-core/lib/logstash/filters/base.rb:175)
org.logstash.config.ir.compiler.AbstractFilterDelegatorExt.multi_filter(org/logstash/config/ir/compiler/AbstractFilterDelegatorExt.java:134)
RUBY.start_workers(/home/andrea/workspace/logstash_andsel/logstash-core/lib/logstash/java_pipeline.rb:301)
```

### PR DESCRIPTION
**Pull request by andsel**
## Release notes
Tag with `_syslogpriparsefailure` on unrecognized `facility_label` code. 

## What does this PR do?

Check the decoded facility code before searching the corresponding label into the lookup table.

## Why is it important/What is the impact to the user?

[RFC 3164](https://www.ietf.org/rfc/rfc3164.txt) in paragraph `4.1.1 PRI Part` provides a full list of the facility codes expected.
When a syslog payload contains an invalid code, instead of crashing the pipeline, it tags the event with `_syslogpriparsefailure`

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- ~~[ ] I have made corresponding change to the default configuration files (and/or docker env variables)~~
- [x] I have added tests that prove my fix is effective or that my feature works

## Author's Checklist

- [ ]

## Related issues

- Fixes #12
- Superseeds #13 

## Logs

```
org.jruby.RubyArray.[](org/jruby/RubyArray.java:1545)
usr.share.logstash.vendor.bundle.jruby.$2_dot_6_dot_0.gems.logstash_minus_filter_minus_syslog_pri_minus_3_dot_1_dot_1.lib.logstash.filters.syslog_pri.parse_pri(logstash-filter-syslog_pri-3.1.1/lib/logstash/filters/syslog_pri.rb:108)
usr.share.logstash.vendor.bundle.jruby.$2_dot_6_dot_0.gems.logstash_minus_filter_minus_syslog_pri_minus_3_dot_1_dot_1.lib.logstash.filters.syslog_pri.filter(logstash-filter-syslog_pri-3.1.1/lib/logstash/filters/syslog_pri.rb:81)
usr.share.logstash.logstash_minus_core.lib.logstash.filters.base.do_filter(/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:159)
usr.share.logstash.logstash_minus_core.lib.logstash.filters.base.multi_filter(/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:178)
org.jruby.RubyArray.each(org/jruby/RubyArray.java:1865)
usr.share.logstash.logstash_minus_core.lib.logstash.filters.base.multi_filter(/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:175)
org.logstash.config.ir.compiler.AbstractFilterDelegatorExt.multi_filter(org/logstash/config/ir/compiler/AbstractFilterDelegatorExt.java:134)
usr.share.logstash.logstash_minus_core.lib.logstash.java_pipeline.start_workers(/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:300)"
```

### CODE REVIEW

**Review by mashhurs — APPROVED** [review]
LGTM!

**Comment by mashhurs** [comment]
Approving before CI finishes since all changes are reasonable. If you face any CI failure, it may be because of jruby bundle exclusion. Please visit [similar case here](https://github.com/logstash-plugins/logstash-input-beats/pull/461/files).

**Comment by andsel** [comment]
Ahh thanks @mashhurs I'll do.
However this PR doesn't solve the expected problem https://github.com/logstash-plugins/logstash-filter-syslog_pri/issues/12, and effectively modifies the behavior, because the actual plugin, if doesn't find the matching label, simply leaves just the code without the label but doesn't refuse to parse it.
The original problem was due to `long` casting before indexing an element in the array, and if that cast fails, generates a RangeError

File: lib/logstash/filters/syslog_pri.rb [hunk 1]
```diff
@@ -104,12 +106,21 @@ def parse_pri(event)
...
-    if @use_labels
-      facility_label = @facility_labels[facility_code]
-      event.set(@facility_label_key, facility_label) if facility_label
-
-      severity_label = @severity_labels[severity_code]
-      event.set(@severity_label_key, severity_label) if severity_label
+    return unless @use_labels
+
+    # from Syslog PRI RFC 4.1.1 PRI Part, facility_code could be at most 124
+    if facility_code > (@facility_labels.size - 1)
```
Comment (mashhurs) [inline lib/logstash/filters/syslog_pri.rb:112]: This is awesome! Thanks.

**Comment by andsel** [comment]
Contrary to my previous [comment](https://github.com/logstash-plugins/logstash-filter-syslog_pri/pull/11#issuecomment-1346792564) this PR effectively solves #12

File: lib/logstash/filters/syslog_pri.rb (hunk 1 above)
Comment (andsel) [reply lib/logstash/filters/syslog_pri.rb:112]: Do you think the PR is still good to be merged?

File: lib/logstash/filters/syslog_pri.rb [hunk 2]
```diff
@@ -104,12 +106,21 @@ def parse_pri(event)
...
     # Add human-readable names after parsing severity and facility from PRI
-    if @use_labels
-      facility_label = @facility_labels[facility_code]
-      event.set(@facility_label_key, facility_label) if facility_label
-
-      severity_label = @severity_labels[severity_code]
-      event.set(@severity_label_key, severity_label) if severity_label
+    return unless @use_labels
+
+    # from Syslog PRI RFC 4.1.1 PRI Part, facility_code could be at most 124
```
Comment (jsvd) [inline lib/logstash/filters/syslog_pri.rb]: facility goes from 0 to 23, where is 124 coming from?

Comment (andsel) [reply lib/logstash/filters/syslog_pri.rb]: The spec says that the priority could be at maximum 999, least 3 significant bits are left for `severity` so the remaining of bits (once `>>3`) represent an integer that could be at maximum 124. 
I'll rephrase the comment as:
```
from Syslog PRI RFC 4.1.1 PRI Part, facility_code the maximum possible value is 124, however it defines just 23 values
```

File: spec/filters/syslog_pri_spec.rb [hunk 3]
```diff
@@ -172,6 +172,15 @@
...
 
+      context "when malformed messages arrive" do
+        let(:syslog_pri) { 250 }
+
+        it "the event is tagged" do
+          subject.filter(event)
+          expect(event.get("tags")).to include("_syslogpriparsefailure")
+        end
+      end
+
```
Comment (jsvd) [inline spec/filters/syslog_pri_spec.rb]: I think it's worth beefing up the tests a bit more to explain exactly what's set and what's not when the value goes above "191" (23 facility, 7 severity):

```suggestion
     context "when malformed messages arrive" do
        context "if syslog priority value is too high" do
          let(:syslog_pri) { 193 }
          let(:syslog_facility_code_field) { ecs_compatibility? ? "[log][syslog][facility][code]" : "syslog_facility_code" }
          let(:syslog_severity_code_field) { ecs_compatibility? ? "[log][syslog][severity][code]" : "syslog_severity_code" }
          let(:syslog_facility_label_field) { ecs_compatibility? ? "[log][syslog][facility][label]" : "syslog_facility" }
          let(:syslog_severity_label_field) { ecs_compatibility? ? "[log][syslog][severity][label]" : "syslog_severity" }

          before(:each) { subject.filter(event) }

          context "if use_labels is enabled (default)" do
            it "the event is tagged" do
              expect(event.get("tags")).to include("_syslogpriparsefailure")
            end
            it "the facility label isn't set" do
              expect(event.get(syslog_facility_label_field)).to be_nil
            end
            it "the severity label isn't set" do
              expect(event.get(syslog_severity_label_field)).to be_nil
            end
          end

          context "if use_labels is disabled" do
            let(:options) { super().merge("use_labels" => false) }
            it "the event is not tagged" do
              expect(event.get("tags")).to be_nil
            end
          end

          it "the facility code is still set" do
            expect(event.get(syslog_facility_code_field)).to eq(24)
          end
          it "the severity code is still set" do
            expect(event.get(syslog_severity_code_field)).to eq(1)
          end
        end
```

Comment (andsel) [reply spec/filters/syslog_pri_spec.rb]: Wonderful, thanks  a lot @jsvd !

**Review by jsvd — APPROVED** [review]
LGTM
